# Generated by Django 3.1.4 on 2020-12-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist_skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.CharField(default='EN-US', max_length=100),
            preserve_default=False,
        ),
    ]
