# Generated by Django 3.1.4 on 2020-12-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist_skill', '0003_auto_20201216_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='word',
            name='example',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
