# Generated by Django 3.1.4 on 2020-12-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist_skill', '0004_auto_20201217_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='urban_definition',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
