# Generated by Django 3.1.4 on 2021-02-13 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('phonetic', models.CharField(blank=True, max_length=100)),
                ('definition', models.TextField(blank=True, max_length=256)),
                ('urban_definition', models.TextField(blank=True, max_length=256)),
                ('example', models.TextField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('words', models.ManyToManyField(to='vocabulary.Word')),
            ],
        ),
    ]
