# Generated by Django 3.1.4 on 2021-02-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='words',
            field=models.ManyToManyField(blank=True, to='vocabulary.Word'),
        ),
    ]
